// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Definition of a Serverless VPC Access connector.
public struct Connector: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name in the format `projects/*/locations/*/connectors/*`.
  public var name: Swift.String = Swift.String()

  /// Name of a VPC network.
  public var network: Swift.String = Swift.String()

  /// The range of internal addresses that follows RFC 4632 notation.
  /// Example: `10.132.0.0/28`.
  public var ipCidrRange: Swift.String = Swift.String()

  /// Output only. State of the VPC access connector.
  public var state: Connector.State = Connector.State()

  /// Minimum throughput of the connector in Mbps. Default and min is 200.
  public var minThroughput: Swift.Int32 = Swift.Int32()

  /// Maximum throughput of the connector in Mbps. Default is 300, max is 1000.
  public var maxThroughput: Swift.Int32 = Swift.Int32()

  /// Output only. List of projects using the connector.
  public var connectedProjects: [Swift.String] = []

  /// The subnet in which to house the VPC Access Connector.
  public var subnet: Connector.Subnet? = nil

  /// Machine type of VM Instance underlying connector. Default is e2-micro
  public var machineType: Swift.String = Swift.String()

  /// Minimum value of instances in autoscaling group underlying the connector.
  public var minInstances: Swift.Int32 = Swift.Int32()

  /// Maximum value of instances in autoscaling group underlying the connector.
  public var maxInstances: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Connector`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Connector().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let network = CodingKeys(stringValue: "network")
    static let ipCidrRange = CodingKeys(stringValue: "ipCidrRange")
    static let state = CodingKeys(stringValue: "state")
    static let minThroughput = CodingKeys(stringValue: "minThroughput")
    static let maxThroughput = CodingKeys(stringValue: "maxThroughput")
    static let connectedProjects = CodingKeys(stringValue: "connectedProjects")
    static let subnet = CodingKeys(stringValue: "subnet")
    static let machineType = CodingKeys(stringValue: "machineType")
    static let minInstances = CodingKeys(stringValue: "minInstances")
    static let maxInstances = CodingKeys(stringValue: "maxInstances")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "network",
      "ipCidrRange",
      "state",
      "minThroughput",
      "maxThroughput",
      "connectedProjects",
      "subnet",
      "machineType",
      "minInstances",
      "maxInstances",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipCidrRange) {
      self.ipCidrRange = value
    }
    if let value = try container.decodeIfPresent(Connector.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minThroughput) {
      self.minThroughput = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxThroughput) {
      self.maxThroughput = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .connectedProjects) {
      self.connectedProjects = value
    }
    self.subnet = try container.decodeIfPresent(Connector.Subnet.self, forKey: .subnet)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .machineType) {
      self.machineType = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minInstances) {
      self.minInstances = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxInstances) {
      self.maxInstances = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.ipCidrRange, forKey: .ipCidrRange)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.minThroughput, forKey: .minThroughput)
    try container.encode(self.maxThroughput, forKey: .maxThroughput)
    try container.encode(self.connectedProjects, forKey: .connectedProjects)
    try container.encodeIfPresent(self.subnet, forKey: .subnet)
    try container.encode(self.machineType, forKey: .machineType)
    try container.encode(self.minInstances, forKey: .minInstances)
    try container.encode(self.maxInstances, forKey: .maxInstances)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The subnet in which to house the connector
  public struct Subnet: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Subnet name (relative, not fully qualified).
    /// E.g. if the full subnet selfLink is
    /// https://compute.googleapis.com/compute/v1/projects/{project}/regions/{region}/subnetworks/{subnetName}
    /// the correct input for this field would be {subnetName}
    public var name: Swift.String = Swift.String()

    /// Project in which the subnet exists.
    /// If not set, this project is assumed to be the project for which
    /// the connector create request was issued.
    public var projectId: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Subnet`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Subnet().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let projectId = CodingKeys(stringValue: "projectId")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "projectId",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
        self.projectId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.projectId, forKey: .projectId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vpcaccess.v1.Connector.Subnet"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// State of a connector.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Invalid state.
    case unspecified
    /// Connector is deployed and ready to receive traffic.
    case ready
    /// An Insert operation is in progress. Transient condition.
    case creating
    /// A Delete operation is in progress. Transient condition.
    case deleting
    /// Connector is in a bad state, manual deletion recommended.
    case error
    /// The connector is being updated.
    case updating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ready: return 1
      case .creating: return 2
      case .deleting: return 3
      case .error: return 4
      case .updating: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .ready: return "READY"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .updating: return "UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "READY": self = .ready
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      case "UPDATING": self = .updating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ready
      case 2: self = .creating
      case 3: self = .deleting
      case 4: self = .error
      case 5: self = .updating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .ready: return try container.encode("READY")
      case .creating: return try container.encode("CREATING")
      case .deleting: return try container.encode("DELETING")
      case .error: return try container.encode("ERROR")
      case .updating: return try container.encode("UPDATING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vpcaccess.v1.Connector"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
