// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Serverless VPC Access API allows users to create and manage connectors for
/// App Engine, Cloud Functions and Cloud Run to have internal connections to
/// Virtual Private Cloud networks.
///
/// @Snippet(path: "VpcAccessServiceQuickstart")
public final class VpcAccessServiceClient: Clients.VpcAccessServiceProtocol, Sendable {
  let inner: any Clients.VpcAccessServiceStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `VpcAccessServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.VpcAccessServiceStub = try Clients.VpcAccessServiceTransport(options)
    inner = Clients.VpcAccessServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.VpcAccessServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a Serverless VPC Access connector, returns an operation.
  ///
  /// @Snippet(path: "VpcAccessService_CreateConnector")
  public func createConnector(
    request: CreateConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createConnector(request: request, options: options)
  }

  /// Creates a Serverless VPC Access connector, returns an operation.
  ///
  /// @Snippet(path: "VpcAccessService_CreateConnector")
  public func createConnectorPollingUntilDone(
    request: CreateConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Connector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Connector>.State
      in
      return try op._extractStatus(Connector.self)
    }
    let rawOp = try await self.createConnector(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Connector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets a Serverless VPC Access connector. Returns NOT_FOUND if the resource
  /// does not exist.
  ///
  /// @Snippet(path: "VpcAccessService_GetConnector")
  public func getConnector(
    request: GetConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVPCAccessV1.Connector {
    try await self.inner.getConnector(request: request, options: options)
  }

  /// Lists Serverless VPC Access connectors.
  ///
  /// @Snippet(path: "VpcAccessService_ListConnectors")
  public func listConnectors(
    request: ListConnectorsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVPCAccessV1.ListConnectorsResponse {
    try await self.inner.listConnectors(request: request, options: options)
  }

  /// Deletes a Serverless VPC Access connector. Returns NOT_FOUND if the
  /// resource does not exist.
  ///
  /// @Snippet(path: "VpcAccessService_DeleteConnector")
  public func deleteConnector(
    request: DeleteConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteConnector(request: request, options: options)
  }

  /// Deletes a Serverless VPC Access connector. Returns NOT_FOUND if the
  /// resource does not exist.
  ///
  /// @Snippet(path: "VpcAccessService_DeleteConnector")
  public func deleteConnectorPollingUntilDone(
    request: DeleteConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteConnector(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "VpcAccessService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VpcAccessService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VpcAccessService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `VpcAccessServiceClient`.
  ///
  /// To mock `VpcAccessServiceClient` change your functions to receive
  /// `some VpcAccessServiceProtocol` or `any VpcAccessServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol VpcAccessServiceProtocol: Sendable {
    /// See `VpcAccessServiceClient.createConnector`.
    func createConnectorPollingUntilDone(request: CreateConnectorRequest) async throws
      -> any GoogleGax.PollableOperation<Connector>

    /// See `VpcAccessServiceClient.createConnector`.
    func createConnectorPollingUntilDone(
      parent: Swift.String,
      connectorId: Swift.String,
      connector: Connector?,
    ) async throws -> any GoogleGax.PollableOperation<Connector>

    /// See `VpcAccessServiceClient.deleteConnector`.
    func deleteConnectorPollingUntilDone(request: DeleteConnectorRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `VpcAccessServiceClient.deleteConnector`.
    func deleteConnectorPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `VpcAccessServiceClient.createConnector`.
    func createConnector(
      request: CreateConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VpcAccessServiceClient.createConnector`.
    func createConnectorPollingUntilDone(
      request: CreateConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Connector>

    /// See `VpcAccessServiceClient.getConnector`.
    func getConnector(
      request: GetConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVPCAccessV1.Connector

    /// See `VpcAccessServiceClient.listConnectors`.
    func listConnectors(
      request: ListConnectorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVPCAccessV1.ListConnectorsResponse

    /// See `VpcAccessServiceClient.deleteConnector`.
    func deleteConnector(
      request: DeleteConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VpcAccessServiceClient.deleteConnector`.
    func deleteConnectorPollingUntilDone(
      request: DeleteConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `VpcAccessServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `VpcAccessServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse
  }
}

// Default implementations
extension Clients.VpcAccessServiceProtocol {
  public func createConnector(request: CreateConnectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createConnector(request: request, options: .init())
  }

  public func createConnector(
    request: CreateConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createConnectorPollingUntilDone(request: CreateConnectorRequest) async throws
    -> any GoogleGax.PollableOperation<Connector>
  {
    try await self.createConnectorPollingUntilDone(request: request, options: .init())
  }

  public func createConnectorPollingUntilDone(
    request: CreateConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Connector> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Connector>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createConnectorPollingUntilDone(
    parent: Swift.String,
    connectorId: Swift.String,
    connector: Connector?,
  ) async throws -> any GoogleGax.PollableOperation<Connector> {
    let request = CreateConnectorRequest().with {
      $0.parent = parent
      $0.connectorId = connectorId
      $0.connector = connector
    }
    return try await self.createConnectorPollingUntilDone(request: request)
  }

  public func getConnector(request: GetConnectorRequest) async throws
    -> GoogleCloudVPCAccessV1.Connector
  {
    try await self.getConnector(request: request, options: .init())
  }

  public func getConnector(
    request: GetConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVPCAccessV1.Connector {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getConnector(
    name: Swift.String,
  ) async throws -> GoogleCloudVPCAccessV1.Connector {
    let request = GetConnectorRequest().with {
      $0.name = name
    }
    return try await self.getConnector(request: request)
  }

  public func listConnectors(request: ListConnectorsRequest) async throws
    -> GoogleCloudVPCAccessV1.ListConnectorsResponse
  {
    try await self.listConnectors(request: request, options: .init())
  }

  public func listConnectors(
    request: ListConnectorsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVPCAccessV1.ListConnectorsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listConnectorsByItems(
    request: ListConnectorsRequest
  ) -> any AsyncSequence<Connector, Swift.Error> {
    self.listConnectorsByItems(request: request, options: .init())
  }

  /// Lists Serverless VPC Access connectors.
  ///
  /// @Snippet(path: "VpcAccessService_ListConnectors")
  public func listConnectorsByItems(
    request: ListConnectorsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Connector, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVPCAccessV1.ListConnectorsResponse in
      var request = request
      request.pageToken = token
      return try await self.listConnectors(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listConnectorsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Connector, Swift.Error> {
    let request = ListConnectorsRequest().with {
      $0.parent = parent
    }
    return self.listConnectorsByItems(request: request)
  }

  public func deleteConnector(request: DeleteConnectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteConnector(request: request, options: .init())
  }

  public func deleteConnector(
    request: DeleteConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteConnectorPollingUntilDone(request: DeleteConnectorRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteConnectorPollingUntilDone(request: request, options: .init())
  }

  public func deleteConnectorPollingUntilDone(
    request: DeleteConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteConnectorPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteConnectorRequest().with {
      $0.name = name
    }
    return try await self.deleteConnectorPollingUntilDone(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "VpcAccessService_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VpcAccessService_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
